# Generated by Django 6.0.1 on 2026-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer_code",
            field=models.CharField(
                blank=True, db_index=True, default="C000", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sale",
            name="region",
            field=models.CharField(db_index=True, default="General", max_length=100),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "date"], name="sales_sale_busines_23d6ce_idx"
            ),
        ),
    ]
