# Generated by Django 6.0.1 on 2026-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["business", "date"], name="expenses_ex_busines_77a46a_idx"
            ),
        ),
    ]
